# Utilizăm o imagine de bază GCC
FROM gcc:latest

# Setăm directorul de lucru în interiorul containerului
WORKDIR /usr/src/app

# Copiem fișierul sursă în directorul curent al containerului
COPY queens.cpp .

# Compilăm codul sursă
RUN g++ -o queens_app queens.cpp

# Comanda care rulează proiectul când containerul este pornit
CMD ["./queens_app"]
